sonar.projectKey=cohort-9-mern-notes-app
sonar.projectName=Cohort 9 MERN Notes App
sonar.host.url=http://localhost:9000

sonar.sources=backend,frontend
sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/coverage/**

sonar.tests=backend
sonar.test.inclusions=backend/**/*.test.js,backend/**/*.spec.js

sonar.javascript.lcov.reportPaths=backend/coverage/lcov.info,frontend/coverage/lcov.info
